#!/bin/bash

# Prepare
export FORCE_COLOR=true
set -e

# Prepare
SELF=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PACKAGES=( "entoj-system" "entoj-html" "entoj-test-fixture" )

# Doit
for i in "${PACKAGES[@]}"
do
	echo "Linking ${i}"
    npm link $i
done
